SCREEN_WIDTH = 878
SCREEN_HEIGHT = 768
SCREEN_TITLE = "TBD Game Name"
FONT_NAME = "Kenney Pixel"

# PLAYER
INITIAL_HEALTH = 5
MOVEMENT_SPEED = 2.0
UPDATES_PER_FRAME = 5

# Constants used to track if the player is facing left or right
LEFT_FACING = 0
RIGHT_FACING = 1
FRONT_FACING = 2
BACK_FACING = 3

# Scene layers
LAYER_NAME_PLAYER = "Player"
LAYER_NAME_ENEMIES = "Enemies"

# Tilemap
TILE_SCALING = 0.75
LEVEL_BORDER_SIZE = 92

SIDEBAR_WIDTH = 110

BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50